// File generated by Antigravity to fix Web crash.
// Note: The appId used for Web here is the Android one, which usually works to bypass the null check. 
// For a production-perfect setup, run `flutterfire configure` to generate this file automatically.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWWtLItMO10lVta87drHP4iPMajVAYXzQ',
    appId: '1:850751814134:web:261f69aa1218befa9dafd7', // Mocked using Android ID
    messagingSenderId: '850751814134',
    projectId: 'burhani-guards-pune',
    authDomain: 'burhani-guards-pune.firebaseapp.com',
    storageBucket: 'burhani-guards-pune.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWtLItMO10lVta87drHP4iPMajVAYXzQ',
    appId: '1:850751814134:android:261f69aa1218befa9dafd7',
    messagingSenderId: '850751814134',
    projectId: 'burhani-guards-pune',
    storageBucket: 'burhani-guards-pune.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWWtLItMO10lVta87drHP4iPMajVAYXzQ',
    appId: '1:850751814134:ios:261f69aa1218befa9dafd7',
    messagingSenderId: '850751814134',
    projectId: 'burhani-guards-pune',
    storageBucket: 'burhani-guards-pune.firebasestorage.app',
  );
}
